schema = 3

[mod]
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.8.0"
    hash = "sha256-C2AAJ7FYEaFpNfVPthM4VZA88TZlF9YmQaJo3xs2cFY="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/aymerick/douceur"]
    version = "v0.2.0"
    hash = "sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE="
  [mod."github.com/catppuccin/go"]
    version = "v0.2.0"
    hash = "sha256-/MZXZD/WlVh75ruSOnq+HlMVNz9vMfpaTIXT//CZU4k="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.18.0"
    hash = "sha256-FVKLet2anNB6gupLYXO4kJaKQIXs1dg2dZ2ooaBiEZU="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.25.0"
    hash = "sha256-A0WjFRFAUhwO3m7uvCOeefPPIM8ReU+xTtIRxG0aH+Y="
  [mod."github.com/charmbracelet/glamour"]
    version = "v0.7.0"
    hash = "sha256-nNEQ6ONSknvXf3hXuQv6N4pWjbCVBATndzzT3jE07eM="
  [mod."github.com/charmbracelet/huh"]
    version = "v0.3.0"
    hash = "sha256-DwXd9lK+klX8fD0n9UmevpRgV2HXO165nCGYRWfdqiM="
  [mod."github.com/charmbracelet/huh/spinner"]
    version = "v0.0.0-20240306161957-71f31c155b08"
    hash = "sha256-FaC8BPMCowvLjTPaTYmawhq2pQgqCkF2+j+za/3s5AY="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.9.1"
    hash = "sha256-AHbabOymgDRIXsMBgJHS25/GgBWT54oGbd15EBWKeZc="
  [mod."github.com/containerd/console"]
    version = "v1.0.4-0.20230313162750-1ae8d489ac81"
    hash = "sha256-Qus81DgpWHJ6RRqeKOKcUFvzCxvPzygJqBabvBsBuHU="
  [mod."github.com/creack/pty"]
    version = "v1.1.21"
    hash = "sha256-pjGw6wQlrVhN65XaIxZueNJqnXThGu00u24rKOLzxS0="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/getsavvyinc/upgrade-cli"]
    version = "v0.6.0"
    hash = "sha256-lDiQu5NeRdrgClxoZZQDmPcBIp/J6aBB/0nEhIBKU+E="
  [mod."github.com/gorilla/css"]
    version = "v1.0.0"
    hash = "sha256-Mmt/IqHpgrtWpbr/AKcJyf/USQTqEuv1HVivY4eHzoQ="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.7.0"
    hash = "sha256-Umc/Q2mxRrPF4aEcDuDJq4lFBT+PSsnyANfyFwUIaxI="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/microcosm-cc/bluemonday"]
    version = "v1.0.25"
    hash = "sha256-/crG5s6cDrJ55nkDBwugLUpY7U+vQuHpCkKm7nnN8Zc="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.2"
    hash = "sha256-Eum/SpyytcNIchANPkG4bYGBgcezLgej7j/+6IhqoMU="
  [mod."github.com/olekukonko/tablewriter"]
    version = "v0.0.5"
    hash = "sha256-/5i70IkH/qSW5KjGzv8aQNKh9tHoz98tqtL0K2DMFn4="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.6"
    hash = "sha256-zGfzO8FWj03POzo47SzrK1B4yLMKJ7iic6ium76ZLzI="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.1-0.20230530133925-c48e322e2a8f"
    hash = "sha256-f2VsDI6G+V2w31tSDzbZPi9EI2E7jRV6Aq8yeOorSZY="
  [mod."github.com/sashabaranov/go-openai"]
    version = "v1.36.0"
    hash = "sha256-XOJ832wO4nTPyvRc7AkNNH/BPQmCGM9V4McX8Dv1J1A="
  [mod."github.com/sethvargo/go-retry"]
    version = "v0.3.0"
    hash = "sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.4"
    hash = "sha256-4he5sGi0uj1LogdqvgpvN8b7p6qlKMGuWXRFzh+FK8s="
  [mod."github.com/yuin/goldmark-emoji"]
    version = "v1.0.2"
    hash = "sha256-RvzhNXlF98fu9SD/Rve9JMtR4bcRh7rN56Twhh/kmt4="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sync"]
    version = "v0.10.0"
    hash = "sha256-HWruKClrdoBKVdxKCyoazxeQV4dIYLdkHekQvx275/o="
  [mod."golang.org/x/sys"]
    version = "v0.28.0"
    hash = "sha256-kzSlDo5FKsQU9cLefIt2dueGUfz9XuEW+mGSGlPATGc="
  [mod."golang.org/x/term"]
    version = "v0.27.0"
    hash = "sha256-cb5p/yOlVL7dbkxugUVfqESTVpZ2LtrUWPnx9yue3r0="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
